// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRtOwsKd-P1eoVtqAZi1VrI4iODJtL3W4',
    appId: '1:574058182343:web:6b7f6cfb2fb7fe2d4e70e2',
    messagingSenderId: '574058182343',
    projectId: 'flutterchatapp-55f0f',
    authDomain: 'flutterchatapp-55f0f.firebaseapp.com',
    storageBucket: 'flutterchatapp-55f0f.appspot.com',
    measurementId: 'G-7W0JHTYN9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbt19PFSBBnxZfoA01KJtstSTvMQA2Xc',
    appId: '1:574058182343:android:7da717fc3ea344024e70e2',
    messagingSenderId: '574058182343',
    projectId: 'flutterchatapp-55f0f',
    storageBucket: 'flutterchatapp-55f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWVNe8THmEjy01HbgMUhgur-QkeKl-a8',
    appId: '1:574058182343:ios:bfe5a3da5c9fcbeb4e70e2',
    messagingSenderId: '574058182343',
    projectId: 'flutterchatapp-55f0f',
    storageBucket: 'flutterchatapp-55f0f.appspot.com',
    iosClientId: '574058182343-u1ao5kd8q52ead3e0ca9qdcsn4mmh18o.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWVNe8THmEjy01HbgMUhgur-QkeKl-a8',
    appId: '1:574058182343:ios:153e998893e2b9bc4e70e2',
    messagingSenderId: '574058182343',
    projectId: 'flutterchatapp-55f0f',
    storageBucket: 'flutterchatapp-55f0f.appspot.com',
    iosClientId: '574058182343-rnmgno79lojlurb6katq8iu4ic5ftsdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
